# -*- coding: utf-8 -*-
"""Average_Siena.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T30GxNc8TylHujBeWuKRGAREaxndtgKs
"""


# Written by Muhammad Farhan Azmine

# import modules
import pandas
import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

from google.colab import drive 
drive.mount('/content/gdrive')

# Read from Reference excel file [https://www.geeksforgeeks.org/read-multiple-csv-files-into-separate-dataframes-in-python/]
file_path1 = "gdrive/My Drive/Siena/Seizures/"
path, dirs, files1 = next(os.walk(file_path1))
file_path2 = "gdrive/My Drive/Siena/NS_Segs/"
path, dirs, files2 = next(os.walk(file_path2))
target=[]
# create empty list
df_list = []
# append datasets to the list [https://www.geeksforgeeks.org/read-multiple-csv-files-into-separate-dataframes-in-python/]
for i in range(len(files1)):
  temp_df = pandas.read_csv(file_path1+files1[i])
  target.append(1)
  df_list.append(temp_df)
for i in range(len(files2)):
  temp_df = pandas.read_csv(file_path2+files2[i])
  target.append(0)
  df_list.append(temp_df)

#For each dataframe in dataframe_list find average peak amplitude per each column
count=0
col_count=0
for df in df_list:
    average=[]
    df = df.rename(columns={'CZ': 'Cz', 'FP2': 'Fp2'})
    for column in df:
     #print(df[column].values)
     average_column = df[column].mean()
     average.append(average_column)
     col_count=col_count+1
    #print('Column count = ', col_count) 
    count=count+1
    col_count=0
    #Combining all values in each file into one dataset
    if count==1 :
      df_average = pandas.DataFrame([average],
                  columns=df.columns.values)
    else:
      df_average_temp=pandas.DataFrame([average],
                  columns=df.columns.values)
      df_average = df_average.append(df_average_temp, ignore_index=True)
      #print(df_write)
    #print (df_write)
      
print('Count of df= ',count)
df_average=df_average[['Fp1','F3','C3','P3','O1','F7','T3','T5','Fc1','Fc5',
                       'Cp1','Cp5','F9','Fz','Cz','Pz','Fp2','F4','C4',
                       'P4','O2','F8','T4','T6','Fc2','Fc6','Cp2','Cp6','F10','EKG EKG','SPO2','HR','1','2']]
df_average=df_average.add_suffix('_avg')
df_average['Target']=target
print(df_average)
df_average.to_csv(r'gdrive/My Drive/Average_Siena.csv', index=False)
