# -*- coding: utf-8 -*-
"""Interspike interval_Siena.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fqrrdOz_yKP9y_GDAP7MMpsL2MEeBYg5
"""

# import modules
import pandas
import os
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import find_peaks


from google.colab import drive 
drive.mount('/content/gdrive')

 
# Read from Reference excel file [https://www.geeksforgeeks.org/read-multiple-csv-files-into-separate-dataframes-in-python/]
file_path1 = "gdrive/My Drive/Siena/Seizures/"
path, dirs, files1 = next(os.walk(file_path1))
file_path2 = "gdrive/My Drive/Siena/NS_Segs/"
path, dirs, files2 = next(os.walk(file_path2))
target=[]
# create empty list
df_list = []
# append datasets to the list [https://www.geeksforgeeks.org/read-multiple-csv-files-into-separate-dataframes-in-python/]
for i in range(len(files1)):
  temp_df = pandas.read_csv(file_path1+files1[i])
  target.append(1)
  df_list.append(temp_df)
for i in range(len(files2)):
  temp_df = pandas.read_csv(file_path2+files2[i])
  target.append(0)
  df_list.append(temp_df)

#For each dataframe in dataframe_list find zero crossings per each column
import math
count=0
col_count=0
for df in df_list:
    interspike_interval=[]
    for column in df:
     #print(df[column].values)
     diff_column = df[column].diff()
     diff_column = diff_column.dropna()
     diff_column = abs(diff_column)
     inter_column = np.median(diff_column)
     interspike_interval.append(inter_column)
     col_count=col_count+1 
    count=count+1
    col_count=0
    #Combining all values in each file into one dataset
    if count==1 :
      df_interspike = pandas.DataFrame([interspike_interval],
                  columns=df.columns.values)
    else:
      df_write_temp=pandas.DataFrame([interspike_interval],
                  columns=df.columns.values)
      df_interspike = df_interspike.append(df_write_temp, ignore_index=True,sort=True)
      #print(df_write)
    #print (df_write)
      
print('Count of df= ',count)
df_interspike=df_interspike[['Fp1','F3','C3','P3','O1','F7','T3','T5','Fc1','Fc5',
                             'Cp1','Cp5','F9','Fz','Cz','Pz','Fp2','F4','C4',
                             'P4','O2','F8','T4','T6','Fc2','Fc6','Cp2','Cp6','F10','EKG EKG','SPO2','HR','1','2']]
df_interspike=df_interspike.add_suffix('_ISI')
df_interspike['Target']=target
print(df_interspike)
df_interspike.to_csv(r'gdrive/My Drive/Interspike_Siena.csv')